### ISSUE TITLE
investigate unused data fetches

### ISSUE THREAD

**Issue by ProgrammerTurnedOutward** [SpencerCornish/belgrade-senior-center#140]
View members seems to fetch all activities that it doesn't use. 

Each create page fetches all items from the type it created (member fetches all member) them redirects without ever using the data. 

These calls can likely be reduced

**Comment by SpencerCornish** [comment]
These are legit, I promise. There are ways to optomize these calls, but they're so low-cost for us, they're effectively a refresh on page change, just to make sure anything new is now present in the page.
