### ISSUE TITLE
talk to client about desired progression

### ISSUE THREAD

**Issue by ProgrammerTurnedOutward** [SpencerCornish/belgrade-senior-center#23]

**Comment by SpencerCornish** [comment]
What does this mean?

**Comment by DanielBachler** [comment]
For contacting the client, if we only have a few questions we can email them to the TA or teacher, who will forward the questions to the client and the answers back to us.  If we wind up having a huge list of questions the teacher can help us set up a meeting to discuss our questions and the project.

**Comment by DanielBachler** [comment]
Will contact teacher to set up a meeting between us and BSC.

**Comment by DanielBachler** [comment]
Emailed current list of questions to our professor to forward to BSC staff.

**Comment by DanielBachler** [comment]
1) Birthday button: They would like one if we can do it
2) Attached is the volunteer form, it contains all the data needed for their volunteers so we can better store it.
[Volunteer Application.pdf](https://github.com/SpencerCornish/belgrade-senior-center/files/2927709/Volunteer.Application.pdf)

**Comment by DanielBachler** [comment]
Taken care of, closing issue.
