### ISSUE TITLE
Collect and classify datatypes for storage

### ISSUE THREAD

**Issue by SpencerCornish** [SpencerCornish/belgrade-senior-center#5]
We need to have an understanding of what different kinds of data we need to store. Collate a list of all atrributes we need to store in the database

AC: A data.md file exists in the repo, listing all the neat things we need to store.

**Comment by DanielBachler** [comment]
I'm going to "merge" this issue with mapping the database schema since in the database everything has a type and most are correct unless the client wants us to use something different.  Closing this but I'll add a comment to the other issue about it.

**Comment by DanielBachler** [comment]
DATA.md created in branch database_info.  Needs review

**Comment by SpencerCornish** [comment]
Merged
