### ISSUE TITLE
Map out a database schema

### ISSUE THREAD

**Issue by SpencerCornish** [SpencerCornish/belgrade-senior-center#6]
Once we have selected a database engine, we can map out a concrete schema, using the respective database engine we select.

AC:  A schema file exists, and accurately portrays our v1 schema.

**Comment by SpencerCornish** [comment]
Just needs polish and customer input

**Comment by DanielBachler** [comment]
Updated based on current documentation, need to thoroughly check the database against documentation, then contact the client for needed clarification.

**Comment by DanielBachler** [comment]
Adding comment from a closed issue, the types of data are present in the database but some may need to be changed if the client foresees a different use than we did.
